# Site settings
title: Er Blog de Arawako
description: 'Conocimiento y cultura libre'
url: 'http://www.arawako.com'
baseurl: '/site/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'José Leonel Subero Gamarra'
  email: arawako@gmail.com
  twitter_username: arawako
#  facebook_username: joshgerdes
  github_username:  arawako
  linkedin_username:  arawako

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
