# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Er' Blog de Arawako
title-normal: Be Free!
email: arawako@gmail.com
description: Another site of a sysadmin Venezolano pro free software, with content released with creative commons license.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://www.arawako.com" # the base hostname & protocol for your site
author: José Leonel SUbero Gamarra
street_address:
city: Caracas
state: DC
zip_code: 1001
country: Venezuela
phone: (716) 555-5555

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
#  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/arawako
gitlab_url: https://gitlab.com/arawako
googleplus_url: https://plus.google.com/u/0/+Jos%C3%A9SuberoArawako
instagram_url:
linkedin_url: https://www.linkedin.com/in/arawako
pinterest_url:
slack_url:
twitter_url: https://twitter.com/arawako

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: arawako
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
